services:
  velora:
    build:
      context: .
      dockerfile: build.dockerfile
    container_name: velora
    restart: always
    env_file:
      - config.env
    ports:
      - "9999:8080"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    environment:
      - APP_ENV=production
