// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_WAITING RoomStatus = 0
	RoomStatus_ROOM_STATUS_STARTED RoomStatus = 1
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_WAITING",
		1: "ROOM_STATUS_STARTED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_WAITING": 0,
		"ROOM_STATUS_STARTED": 1,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StartGameRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequestMessage) Reset() {
	*x = StartGameRequestMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequestMessage) ProtoMessage() {}

func (x *StartGameRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequestMessage.ProtoReflect.Descriptor instead.
func (*StartGameRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayer     uint32                 `protobuf:"varint,1,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequestMessage) Reset() {
	*x = CreateRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequestMessage) ProtoMessage() {}

func (x *CreateRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*CreateRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomRequestMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *CreateRoomRequestMessage) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type JoinRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequestMessage) Reset() {
	*x = JoinRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequestMessage) ProtoMessage() {}

func (x *JoinRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*JoinRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomRequestMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomListRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequestMessage) Reset() {
	*x = RoomListRequestMessage{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequestMessage) ProtoMessage() {}

func (x *RoomListRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequestMessage.ProtoReflect.Descriptor instead.
func (*RoomListRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

type RoomSummaryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Players       []*RoomPlayerMessage   `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`
	MaxPlayer     uint32                 `protobuf:"varint,4,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Status        RoomStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=packets.RoomStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSummaryMessage) Reset() {
	*x = RoomSummaryMessage{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSummaryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSummaryMessage) ProtoMessage() {}

func (x *RoomSummaryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSummaryMessage.ProtoReflect.Descriptor instead.
func (*RoomSummaryMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *RoomSummaryMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomSummaryMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomSummaryMessage) GetPlayers() []*RoomPlayerMessage {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomSummaryMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *RoomSummaryMessage) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_WAITING
}

type RoomListSnapshotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomSummaryMessage  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListSnapshotMessage) Reset() {
	*x = RoomListSnapshotMessage{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListSnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListSnapshotMessage) ProtoMessage() {}

func (x *RoomListSnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListSnapshotMessage.ProtoReflect.Descriptor instead.
func (*RoomListSnapshotMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *RoomListSnapshotMessage) GetRooms() []*RoomSummaryMessage {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type LeaveRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequestMessage) Reset() {
	*x = LeaveRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequestMessage) ProtoMessage() {}

func (x *LeaveRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

type ReadyRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequestMessage) Reset() {
	*x = ReadyRequestMessage{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequestMessage) ProtoMessage() {}

func (x *ReadyRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequestMessage.ProtoReflect.Descriptor instead.
func (*ReadyRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *ReadyRequestMessage) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type RoomPlayerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	IsReady       bool                   `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Owner         bool                   `protobuf:"varint,5,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPlayerMessage) Reset() {
	*x = RoomPlayerMessage{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerMessage) ProtoMessage() {}

func (x *RoomPlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerMessage.ProtoReflect.Descriptor instead.
func (*RoomPlayerMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *RoomPlayerMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomPlayerMessage) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RoomPlayerMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomPlayerMessage) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *RoomPlayerMessage) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type RoomStateSnapshotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MaxPlayer     uint32                 `protobuf:"varint,2,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Status        RoomStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=packets.RoomStatus" json:"status,omitempty"`
	Player        []*RoomPlayerMessage   `protobuf:"bytes,4,rep,name=Player,proto3" json:"Player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateSnapshotMessage) Reset() {
	*x = RoomStateSnapshotMessage{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateSnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateSnapshotMessage) ProtoMessage() {}

func (x *RoomStateSnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateSnapshotMessage.ProtoReflect.Descriptor instead.
func (*RoomStateSnapshotMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *RoomStateSnapshotMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomStateSnapshotMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *RoomStateSnapshotMessage) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_WAITING
}

func (x *RoomStateSnapshotMessage) GetPlayer() []*RoomPlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type MatchStartingMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	StartsAtUnixMs int64                  `protobuf:"varint,2,opt,name=startsAtUnixMs,proto3" json:"startsAtUnixMs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchStartingMessage) Reset() {
	*x = MatchStartingMessage{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartingMessage) ProtoMessage() {}

func (x *MatchStartingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartingMessage.ProtoReflect.Descriptor instead.
func (*MatchStartingMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *MatchStartingMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MatchStartingMessage) GetStartsAtUnixMs() int64 {
	if x != nil {
		return x.StartsAtUnixMs
	}
	return 0
}

type MatchStartMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MatchId       uint64                 `protobuf:"varint,2,opt,name=matchId,proto3" json:"matchId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartMessage) Reset() {
	*x = MatchStartMessage{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartMessage) ProtoMessage() {}

func (x *MatchStartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartMessage.ProtoReflect.Descriptor instead.
func (*MatchStartMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *MatchStartMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MatchStartMessage) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_CreateRoomRequest
	//	*Packet_JoinRoomRequest
	//	*Packet_LeaveRoomRequest
	//	*Packet_ReadyRequest
	//	*Packet_RoomStateSnapshot
	//	*Packet_MatchStarted
	//	*Packet_StartGame
	//	*Packet_RoomList
	//	*Packet_RoomSummaryMessage
	//	*Packet_RoomListSnapshot
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetCreateRoomRequest() *CreateRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoomRequest); ok {
			return x.CreateRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomRequest() *JoinRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomRequest); ok {
			return x.JoinRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetLeaveRoomRequest() *LeaveRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LeaveRoomRequest); ok {
			return x.LeaveRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetReadyRequest() *ReadyRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ReadyRequest); ok {
			return x.ReadyRequest
		}
	}
	return nil
}

func (x *Packet) GetRoomStateSnapshot() *RoomStateSnapshotMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomStateSnapshot); ok {
			return x.RoomStateSnapshot
		}
	}
	return nil
}

func (x *Packet) GetMatchStarted() *MatchStartMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *Packet) GetStartGame() *StartGameRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *Packet) GetRoomList() *RoomListRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomList); ok {
			return x.RoomList
		}
	}
	return nil
}

func (x *Packet) GetRoomSummaryMessage() *RoomSummaryMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomSummaryMessage); ok {
			return x.RoomSummaryMessage
		}
	}
	return nil
}

func (x *Packet) GetRoomListSnapshot() *RoomListSnapshotMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomListSnapshot); ok {
			return x.RoomListSnapshot
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,4,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,5,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponseMessage `protobuf:"bytes,6,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,7,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_CreateRoomRequest struct {
	CreateRoomRequest *CreateRoomRequestMessage `protobuf:"bytes,8,opt,name=create_room_request,json=createRoomRequest,proto3,oneof"`
}

type Packet_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequestMessage `protobuf:"bytes,9,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type Packet_LeaveRoomRequest struct {
	LeaveRoomRequest *LeaveRoomRequestMessage `protobuf:"bytes,10,opt,name=leave_room_request,json=leaveRoomRequest,proto3,oneof"`
}

type Packet_ReadyRequest struct {
	ReadyRequest *ReadyRequestMessage `protobuf:"bytes,11,opt,name=ready_request,json=readyRequest,proto3,oneof"`
}

type Packet_RoomStateSnapshot struct {
	RoomStateSnapshot *RoomStateSnapshotMessage `protobuf:"bytes,12,opt,name=room_state_snapshot,json=roomStateSnapshot,proto3,oneof"`
}

type Packet_MatchStarted struct {
	MatchStarted *MatchStartMessage `protobuf:"bytes,13,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type Packet_StartGame struct {
	StartGame *StartGameRequestMessage `protobuf:"bytes,14,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Packet_RoomList struct {
	RoomList *RoomListRequestMessage `protobuf:"bytes,15,opt,name=room_list,json=roomList,proto3,oneof"`
}

type Packet_RoomSummaryMessage struct {
	RoomSummaryMessage *RoomSummaryMessage `protobuf:"bytes,16,opt,name=room_summary_message,json=roomSummaryMessage,proto3,oneof"`
}

type Packet_RoomListSnapshot struct {
	RoomListSnapshot *RoomListSnapshotMessage `protobuf:"bytes,17,opt,name=room_list_snapshot,json=roomListSnapshot,proto3,oneof"`
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_CreateRoomRequest) isPacket_Msg() {}

func (*Packet_JoinRoomRequest) isPacket_Msg() {}

func (*Packet_LeaveRoomRequest) isPacket_Msg() {}

func (*Packet_ReadyRequest) isPacket_Msg() {}

func (*Packet_RoomStateSnapshot) isPacket_Msg() {}

func (*Packet_MatchStarted) isPacket_Msg() {}

func (*Packet_StartGame) isPacket_Msg() {}

func (*Packet_RoomList) isPacket_Msg() {}

func (*Packet_RoomSummaryMessage) isPacket_Msg() {}

func (*Packet_RoomListSnapshot) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x19\n" +
	"\x17StartGameRequestMessage\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\x18CreateRoomRequestMessage\x12\x1c\n" +
	"\tmaxPlayer\x18\x01 \x01(\rR\tmaxPlayer\x12\x1a\n" +
	"\broomName\x18\x02 \x01(\tR\broomName\"0\n" +
	"\x16JoinRoomRequestMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\"\x18\n" +
	"\x16RoomListRequestMessage\"\xc1\x01\n" +
	"\x12RoomSummaryMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\x04R\x06roomId\x124\n" +
	"\aPlayers\x18\x03 \x03(\v2\x1a.packets.RoomPlayerMessageR\aPlayers\x12\x1c\n" +
	"\tmaxPlayer\x18\x04 \x01(\rR\tmaxPlayer\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.packets.RoomStatusR\x06status\"L\n" +
	"\x17RoomListSnapshotMessage\x121\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1b.packets.RoomSummaryMessageR\x05rooms\"\x19\n" +
	"\x17LeaveRoomRequestMessage\"/\n" +
	"\x13ReadyRequestMessage\x12\x18\n" +
	"\aisReady\x18\x01 \x01(\bR\aisReady\"\x93\x01\n" +
	"\x11RoomPlayerMessage\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\x04R\bclientId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x18\n" +
	"\aisReady\x18\x04 \x01(\bR\aisReady\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\bR\x05owner\"\xb1\x01\n" +
	"\x18RoomStateSnapshotMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\x12\x1c\n" +
	"\tmaxPlayer\x18\x02 \x01(\rR\tmaxPlayer\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.packets.RoomStatusR\x06status\x122\n" +
	"\x06Player\x18\x04 \x03(\v2\x1a.packets.RoomPlayerMessageR\x06Player\"V\n" +
	"\x14MatchStartingMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\x12&\n" +
	"\x0estartsAtUnixMs\x18\x02 \x01(\x03R\x0estartsAtUnixMs\"E\n" +
	"\x11MatchStartMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\x12\x18\n" +
	"\amatchId\x18\x02 \x01(\x04R\amatchId\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x8e\t\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x03 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12C\n" +
	"\rlogin_request\x18\x04 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x05 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\x06 \x01(\v2\x1a.packets.OkResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\a \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12S\n" +
	"\x13create_room_request\x18\b \x01(\v2!.packets.CreateRoomRequestMessageH\x00R\x11createRoomRequest\x12M\n" +
	"\x11join_room_request\x18\t \x01(\v2\x1f.packets.JoinRoomRequestMessageH\x00R\x0fjoinRoomRequest\x12P\n" +
	"\x12leave_room_request\x18\n" +
	" \x01(\v2 .packets.LeaveRoomRequestMessageH\x00R\x10leaveRoomRequest\x12C\n" +
	"\rready_request\x18\v \x01(\v2\x1c.packets.ReadyRequestMessageH\x00R\freadyRequest\x12S\n" +
	"\x13room_state_snapshot\x18\f \x01(\v2!.packets.RoomStateSnapshotMessageH\x00R\x11roomStateSnapshot\x12A\n" +
	"\rmatch_started\x18\r \x01(\v2\x1a.packets.MatchStartMessageH\x00R\fmatchStarted\x12A\n" +
	"\n" +
	"start_game\x18\x0e \x01(\v2 .packets.StartGameRequestMessageH\x00R\tstartGame\x12>\n" +
	"\troom_list\x18\x0f \x01(\v2\x1f.packets.RoomListRequestMessageH\x00R\broomList\x12O\n" +
	"\x14room_summary_message\x18\x10 \x01(\v2\x1b.packets.RoomSummaryMessageH\x00R\x12roomSummaryMessage\x12P\n" +
	"\x12room_list_snapshot\x18\x11 \x01(\v2 .packets.RoomListSnapshotMessageH\x00R\x10roomListSnapshotB\x05\n" +
	"\x03msg*>\n" +
	"\n" +
	"RoomStatus\x12\x17\n" +
	"\x13ROOM_STATUS_WAITING\x10\x00\x12\x17\n" +
	"\x13ROOM_STATUS_STARTED\x10\x01B\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_packets_proto_goTypes = []any{
	(RoomStatus)(0),                  // 0: packets.RoomStatus
	(*ChatMessage)(nil),              // 1: packets.ChatMessage
	(*IdMessage)(nil),                // 2: packets.IdMessage
	(*StartGameRequestMessage)(nil),  // 3: packets.StartGameRequestMessage
	(*LoginRequestMessage)(nil),      // 4: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil),   // 5: packets.RegisterRequestMessage
	(*CreateRoomRequestMessage)(nil), // 6: packets.CreateRoomRequestMessage
	(*JoinRoomRequestMessage)(nil),   // 7: packets.JoinRoomRequestMessage
	(*RoomListRequestMessage)(nil),   // 8: packets.RoomListRequestMessage
	(*RoomSummaryMessage)(nil),       // 9: packets.RoomSummaryMessage
	(*RoomListSnapshotMessage)(nil),  // 10: packets.RoomListSnapshotMessage
	(*LeaveRoomRequestMessage)(nil),  // 11: packets.LeaveRoomRequestMessage
	(*ReadyRequestMessage)(nil),      // 12: packets.ReadyRequestMessage
	(*RoomPlayerMessage)(nil),        // 13: packets.RoomPlayerMessage
	(*RoomStateSnapshotMessage)(nil), // 14: packets.RoomStateSnapshotMessage
	(*MatchStartingMessage)(nil),     // 15: packets.MatchStartingMessage
	(*MatchStartMessage)(nil),        // 16: packets.MatchStartMessage
	(*OkResponseMessage)(nil),        // 17: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),      // 18: packets.DenyResponseMessage
	(*Packet)(nil),                   // 19: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	13, // 0: packets.RoomSummaryMessage.Players:type_name -> packets.RoomPlayerMessage
	0,  // 1: packets.RoomSummaryMessage.status:type_name -> packets.RoomStatus
	9,  // 2: packets.RoomListSnapshotMessage.rooms:type_name -> packets.RoomSummaryMessage
	0,  // 3: packets.RoomStateSnapshotMessage.status:type_name -> packets.RoomStatus
	13, // 4: packets.RoomStateSnapshotMessage.Player:type_name -> packets.RoomPlayerMessage
	1,  // 5: packets.Packet.chat:type_name -> packets.ChatMessage
	2,  // 6: packets.Packet.id:type_name -> packets.IdMessage
	4,  // 7: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	5,  // 8: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	17, // 9: packets.Packet.ok_response:type_name -> packets.OkResponseMessage
	18, // 10: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	6,  // 11: packets.Packet.create_room_request:type_name -> packets.CreateRoomRequestMessage
	7,  // 12: packets.Packet.join_room_request:type_name -> packets.JoinRoomRequestMessage
	11, // 13: packets.Packet.leave_room_request:type_name -> packets.LeaveRoomRequestMessage
	12, // 14: packets.Packet.ready_request:type_name -> packets.ReadyRequestMessage
	14, // 15: packets.Packet.room_state_snapshot:type_name -> packets.RoomStateSnapshotMessage
	16, // 16: packets.Packet.match_started:type_name -> packets.MatchStartMessage
	3,  // 17: packets.Packet.start_game:type_name -> packets.StartGameRequestMessage
	8,  // 18: packets.Packet.room_list:type_name -> packets.RoomListRequestMessage
	9,  // 19: packets.Packet.room_summary_message:type_name -> packets.RoomSummaryMessage
	10, // 20: packets.Packet.room_list_snapshot:type_name -> packets.RoomListSnapshotMessage
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[18].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_CreateRoomRequest)(nil),
		(*Packet_JoinRoomRequest)(nil),
		(*Packet_LeaveRoomRequest)(nil),
		(*Packet_ReadyRequest)(nil),
		(*Packet_RoomStateSnapshot)(nil),
		(*Packet_MatchStarted)(nil),
		(*Packet_StartGame)(nil),
		(*Packet_RoomList)(nil),
		(*Packet_RoomSummaryMessage)(nil),
		(*Packet_RoomListSnapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
