// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_WAITING RoomStatus = 0
	RoomStatus_ROOM_STATUS_STARTED RoomStatus = 1
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_WAITING",
		1: "ROOM_STATUS_STARTED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_WAITING": 0,
		"ROOM_STATUS_STARTED": 1,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type MatchPhase int32

const (
	MatchPhase_MATCH_PHASE_PREPARE MatchPhase = 0
	MatchPhase_MATCH_PHASE_ACTIVE  MatchPhase = 1
	MatchPhase_MATCH_PHASE_ENDED   MatchPhase = 2
)

// Enum value maps for MatchPhase.
var (
	MatchPhase_name = map[int32]string{
		0: "MATCH_PHASE_PREPARE",
		1: "MATCH_PHASE_ACTIVE",
		2: "MATCH_PHASE_ENDED",
	}
	MatchPhase_value = map[string]int32{
		"MATCH_PHASE_PREPARE": 0,
		"MATCH_PHASE_ACTIVE":  1,
		"MATCH_PHASE_ENDED":   2,
	}
)

func (x MatchPhase) Enum() *MatchPhase {
	p := new(MatchPhase)
	*p = x
	return p
}

func (x MatchPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (MatchPhase) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x MatchPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchPhase.Descriptor instead.
func (MatchPhase) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StartGameRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequestMessage) Reset() {
	*x = StartGameRequestMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequestMessage) ProtoMessage() {}

func (x *StartGameRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequestMessage.ProtoReflect.Descriptor instead.
func (*StartGameRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

type LoginRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestMessage) Reset() {
	*x = RegisterRequestMessage{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestMessage) ProtoMessage() {}

func (x *RegisterRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayer     uint32                 `protobuf:"varint,1,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequestMessage) Reset() {
	*x = CreateRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequestMessage) ProtoMessage() {}

func (x *CreateRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*CreateRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomRequestMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *CreateRoomRequestMessage) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type JoinRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequestMessage) Reset() {
	*x = JoinRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequestMessage) ProtoMessage() {}

func (x *JoinRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*JoinRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomRequestMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomListRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequestMessage) Reset() {
	*x = RoomListRequestMessage{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequestMessage) ProtoMessage() {}

func (x *RoomListRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequestMessage.ProtoReflect.Descriptor instead.
func (*RoomListRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

type RoomSummaryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Players       []*RoomPlayerMessage   `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`
	MaxPlayer     uint32                 `protobuf:"varint,4,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Status        RoomStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=packets.RoomStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSummaryMessage) Reset() {
	*x = RoomSummaryMessage{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSummaryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSummaryMessage) ProtoMessage() {}

func (x *RoomSummaryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSummaryMessage.ProtoReflect.Descriptor instead.
func (*RoomSummaryMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *RoomSummaryMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomSummaryMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomSummaryMessage) GetPlayers() []*RoomPlayerMessage {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomSummaryMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *RoomSummaryMessage) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_WAITING
}

type RoomListSnapshotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomSummaryMessage  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListSnapshotMessage) Reset() {
	*x = RoomListSnapshotMessage{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListSnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListSnapshotMessage) ProtoMessage() {}

func (x *RoomListSnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListSnapshotMessage.ProtoReflect.Descriptor instead.
func (*RoomListSnapshotMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *RoomListSnapshotMessage) GetRooms() []*RoomSummaryMessage {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type LeaveRoomRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequestMessage) Reset() {
	*x = LeaveRoomRequestMessage{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequestMessage) ProtoMessage() {}

func (x *LeaveRoomRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequestMessage.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

type ReadyRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=isReady,proto3" json:"isReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequestMessage) Reset() {
	*x = ReadyRequestMessage{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequestMessage) ProtoMessage() {}

func (x *ReadyRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequestMessage.ProtoReflect.Descriptor instead.
func (*ReadyRequestMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *ReadyRequestMessage) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type ReadyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsReady       bool                   `protobuf:"varint,2,opt,name=isReady,proto3" json:"isReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponseMessage) Reset() {
	*x = ReadyResponseMessage{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponseMessage) ProtoMessage() {}

func (x *ReadyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponseMessage.ProtoReflect.Descriptor instead.
func (*ReadyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *ReadyResponseMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadyResponseMessage) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type RoomPlayerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	IsReady       bool                   `protobuf:"varint,4,opt,name=isReady,proto3" json:"isReady,omitempty"`
	Owner         bool                   `protobuf:"varint,5,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPlayerMessage) Reset() {
	*x = RoomPlayerMessage{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerMessage) ProtoMessage() {}

func (x *RoomPlayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerMessage.ProtoReflect.Descriptor instead.
func (*RoomPlayerMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *RoomPlayerMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomPlayerMessage) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RoomPlayerMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomPlayerMessage) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *RoomPlayerMessage) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type JoinRoomResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *RoomPlayerMessage     `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponseMessage) Reset() {
	*x = JoinRoomResponseMessage{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponseMessage) ProtoMessage() {}

func (x *JoinRoomResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponseMessage.ProtoReflect.Descriptor instead.
func (*JoinRoomResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *JoinRoomResponseMessage) GetPlayer() *RoomPlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerKickRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerKickRoomResponse) Reset() {
	*x = PlayerKickRoomResponse{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerKickRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerKickRoomResponse) ProtoMessage() {}

func (x *PlayerKickRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerKickRoomResponse.ProtoReflect.Descriptor instead.
func (*PlayerKickRoomResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerKickRoomResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PlayerKickRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerKickRoomRequest) Reset() {
	*x = PlayerKickRoomRequest{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerKickRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerKickRoomRequest) ProtoMessage() {}

func (x *PlayerKickRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerKickRoomRequest.ProtoReflect.Descriptor instead.
func (*PlayerKickRoomRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerKickRoomRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PlayerRemoveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *RoomPlayerMessage     `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRemoveRoom) Reset() {
	*x = PlayerRemoveRoom{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRemoveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRemoveRoom) ProtoMessage() {}

func (x *PlayerRemoveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRemoveRoom.ProtoReflect.Descriptor instead.
func (*PlayerRemoveRoom) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerRemoveRoom) GetPlayer() *RoomPlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayersInRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersInRoomRequest) Reset() {
	*x = PlayersInRoomRequest{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersInRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersInRoomRequest) ProtoMessage() {}

func (x *PlayersInRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersInRoomRequest.ProtoReflect.Descriptor instead.
func (*PlayersInRoomRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *PlayersInRoomRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type PlayersInRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        []*RoomPlayerMessage   `protobuf:"bytes,1,rep,name=Player,proto3" json:"Player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersInRoomResponse) Reset() {
	*x = PlayersInRoomResponse{}
	mi := &file_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersInRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersInRoomResponse) ProtoMessage() {}

func (x *PlayersInRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersInRoomResponse.ProtoReflect.Descriptor instead.
func (*PlayersInRoomResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{19}
}

func (x *PlayersInRoomResponse) GetPlayer() []*RoomPlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type RoomStateSnapshotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MaxPlayer     uint32                 `protobuf:"varint,2,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	Status        RoomStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=packets.RoomStatus" json:"status,omitempty"`
	Player        []*RoomPlayerMessage   `protobuf:"bytes,4,rep,name=Player,proto3" json:"Player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateSnapshotMessage) Reset() {
	*x = RoomStateSnapshotMessage{}
	mi := &file_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateSnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateSnapshotMessage) ProtoMessage() {}

func (x *RoomStateSnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateSnapshotMessage.ProtoReflect.Descriptor instead.
func (*RoomStateSnapshotMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{20}
}

func (x *RoomStateSnapshotMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomStateSnapshotMessage) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *RoomStateSnapshotMessage) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_WAITING
}

func (x *RoomStateSnapshotMessage) GetPlayer() []*RoomPlayerMessage {
	if x != nil {
		return x.Player
	}
	return nil
}

type MatchStartMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MatchId        uint64                 `protobuf:"varint,2,opt,name=matchId,proto3" json:"matchId,omitempty"`
	PlayerId       uint64                 `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Slot           uint32                 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	MapSeed        uint64                 `protobuf:"varint,5,opt,name=mapSeed,proto3" json:"mapSeed,omitempty"`
	StartsAtUnixMs int64                  `protobuf:"varint,6,opt,name=startsAtUnixMs,proto3" json:"startsAtUnixMs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchStartMessage) Reset() {
	*x = MatchStartMessage{}
	mi := &file_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartMessage) ProtoMessage() {}

func (x *MatchStartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartMessage.ProtoReflect.Descriptor instead.
func (*MatchStartMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{21}
}

func (x *MatchStartMessage) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MatchStartMessage) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *MatchStartMessage) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MatchStartMessage) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *MatchStartMessage) GetMapSeed() uint64 {
	if x != nil {
		return x.MapSeed
	}
	return 0
}

func (x *MatchStartMessage) GetStartsAtUnixMs() int64 {
	if x != nil {
		return x.StartsAtUnixMs
	}
	return 0
}

type Vector2Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2Message) Reset() {
	*x = Vector2Message{}
	mi := &file_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2Message) ProtoMessage() {}

func (x *Vector2Message) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2Message.ProtoReflect.Descriptor instead.
func (*Vector2Message) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{22}
}

func (x *Vector2Message) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2Message) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerInputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       uint64                 `protobuf:"varint,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	MovePosition  *Vector2Message        `protobuf:"bytes,2,opt,name=movePosition,proto3" json:"movePosition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInputMessage) Reset() {
	*x = PlayerInputMessage{}
	mi := &file_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInputMessage) ProtoMessage() {}

func (x *PlayerInputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInputMessage.ProtoReflect.Descriptor instead.
func (*PlayerInputMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerInputMessage) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *PlayerInputMessage) GetMovePosition() *Vector2Message {
	if x != nil {
		return x.MovePosition
	}
	return nil
}

type PlayerCellEntityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Position      *Vector2Message        `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Hp            uint32                 `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	Biomass       uint32                 `protobuf:"varint,5,opt,name=biomass,proto3" json:"biomass,omitempty"`
	Level         uint32                 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Alive         bool                   `protobuf:"varint,7,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCellEntityMessage) Reset() {
	*x = PlayerCellEntityMessage{}
	mi := &file_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCellEntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCellEntityMessage) ProtoMessage() {}

func (x *PlayerCellEntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCellEntityMessage.ProtoReflect.Descriptor instead.
func (*PlayerCellEntityMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{24}
}

func (x *PlayerCellEntityMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerCellEntityMessage) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PlayerCellEntityMessage) GetPosition() *Vector2Message {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerCellEntityMessage) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerCellEntityMessage) GetBiomass() uint32 {
	if x != nil {
		return x.Biomass
	}
	return 0
}

func (x *PlayerCellEntityMessage) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerCellEntityMessage) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type CoreEntityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Position      *Vector2Message        `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Hp            uint32                 `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreEntityMessage) Reset() {
	*x = CoreEntityMessage{}
	mi := &file_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreEntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreEntityMessage) ProtoMessage() {}

func (x *CoreEntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreEntityMessage.ProtoReflect.Descriptor instead.
func (*CoreEntityMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{25}
}

func (x *CoreEntityMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CoreEntityMessage) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CoreEntityMessage) GetPosition() *Vector2Message {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CoreEntityMessage) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type NutrientEntityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2Message        `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Value         uint32                 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NutrientEntityMessage) Reset() {
	*x = NutrientEntityMessage{}
	mi := &file_packets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NutrientEntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutrientEntityMessage) ProtoMessage() {}

func (x *NutrientEntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutrientEntityMessage.ProtoReflect.Descriptor instead.
func (*NutrientEntityMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{26}
}

func (x *NutrientEntityMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NutrientEntityMessage) GetPosition() *Vector2Message {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NutrientEntityMessage) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NutrientEntityMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type WallEntityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WallEntityMessage) Reset() {
	*x = WallEntityMessage{}
	mi := &file_packets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WallEntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WallEntityMessage) ProtoMessage() {}

func (x *WallEntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WallEntityMessage.ProtoReflect.Descriptor instead.
func (*WallEntityMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{27}
}

func (x *WallEntityMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WallEntityMessage) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

type MatchSnapshotMessage struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	MatchId         uint64                     `protobuf:"varint,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	ServerTick      uint64                     `protobuf:"varint,2,opt,name=serverTick,proto3" json:"serverTick,omitempty"`
	Phase           MatchPhase                 `protobuf:"varint,3,opt,name=phase,proto3,enum=packets.MatchPhase" json:"phase,omitempty"`
	PhaseTimeLeftMs int64                      `protobuf:"varint,4,opt,name=phaseTimeLeftMs,proto3" json:"phaseTimeLeftMs,omitempty"`
	PlayerCells     []*PlayerCellEntityMessage `protobuf:"bytes,5,rep,name=playerCells,proto3" json:"playerCells,omitempty"`
	Cores           []*CoreEntityMessage       `protobuf:"bytes,6,rep,name=cores,proto3" json:"cores,omitempty"`
	Nutrients       []*NutrientEntityMessage   `protobuf:"bytes,7,rep,name=nutrients,proto3" json:"nutrients,omitempty"`
	Walls           []*WallEntityMessage       `protobuf:"bytes,8,rep,name=walls,proto3" json:"walls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchSnapshotMessage) Reset() {
	*x = MatchSnapshotMessage{}
	mi := &file_packets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchSnapshotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchSnapshotMessage) ProtoMessage() {}

func (x *MatchSnapshotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchSnapshotMessage.ProtoReflect.Descriptor instead.
func (*MatchSnapshotMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{28}
}

func (x *MatchSnapshotMessage) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *MatchSnapshotMessage) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *MatchSnapshotMessage) GetPhase() MatchPhase {
	if x != nil {
		return x.Phase
	}
	return MatchPhase_MATCH_PHASE_PREPARE
}

func (x *MatchSnapshotMessage) GetPhaseTimeLeftMs() int64 {
	if x != nil {
		return x.PhaseTimeLeftMs
	}
	return 0
}

func (x *MatchSnapshotMessage) GetPlayerCells() []*PlayerCellEntityMessage {
	if x != nil {
		return x.PlayerCells
	}
	return nil
}

func (x *MatchSnapshotMessage) GetCores() []*CoreEntityMessage {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *MatchSnapshotMessage) GetNutrients() []*NutrientEntityMessage {
	if x != nil {
		return x.Nutrients
	}
	return nil
}

func (x *MatchSnapshotMessage) GetWalls() []*WallEntityMessage {
	if x != nil {
		return x.Walls
	}
	return nil
}

type OkResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponseMessage) Reset() {
	*x = OkResponseMessage{}
	mi := &file_packets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponseMessage) ProtoMessage() {}

func (x *OkResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponseMessage.ProtoReflect.Descriptor instead.
func (*OkResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{29}
}

type DenyResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponseMessage) Reset() {
	*x = DenyResponseMessage{}
	mi := &file_packets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponseMessage) ProtoMessage() {}

func (x *DenyResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponseMessage.ProtoReflect.Descriptor instead.
func (*DenyResponseMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{30}
}

func (x *DenyResponseMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Id
	//	*Packet_LoginRequest
	//	*Packet_RegisterRequest
	//	*Packet_OkResponse
	//	*Packet_DenyResponse
	//	*Packet_CreateRoomRequest
	//	*Packet_JoinRoomRequest
	//	*Packet_LeaveRoomRequest
	//	*Packet_ReadyRequest
	//	*Packet_ReadyResponse
	//	*Packet_RoomStateSnapshot
	//	*Packet_MatchStarted
	//	*Packet_StartGame
	//	*Packet_RoomSummaryMessage
	//	*Packet_RoomListSnapshot
	//	*Packet_PlayerInput
	//	*Packet_MatchSnapshot
	//	*Packet_PlayerKickRoomRequest
	//	*Packet_PlayerKickRoomResponse
	//	*Packet_PlayerRemoveRoom
	//	*Packet_JoinRoomResponseMessage
	//	*Packet_PlayersInRoomRequest
	//	*Packet_PlayersInRoomResponse
	//	*Packet_RoomListRequestMessage
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{31}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetCreateRoomRequest() *CreateRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoomRequest); ok {
			return x.CreateRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomRequest() *JoinRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomRequest); ok {
			return x.JoinRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetLeaveRoomRequest() *LeaveRoomRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LeaveRoomRequest); ok {
			return x.LeaveRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetReadyRequest() *ReadyRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ReadyRequest); ok {
			return x.ReadyRequest
		}
	}
	return nil
}

func (x *Packet) GetReadyResponse() *ReadyResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_ReadyResponse); ok {
			return x.ReadyResponse
		}
	}
	return nil
}

func (x *Packet) GetRoomStateSnapshot() *RoomStateSnapshotMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomStateSnapshot); ok {
			return x.RoomStateSnapshot
		}
	}
	return nil
}

func (x *Packet) GetMatchStarted() *MatchStartMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *Packet) GetStartGame() *StartGameRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *Packet) GetRoomSummaryMessage() *RoomSummaryMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomSummaryMessage); ok {
			return x.RoomSummaryMessage
		}
	}
	return nil
}

func (x *Packet) GetRoomListSnapshot() *RoomListSnapshotMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomListSnapshot); ok {
			return x.RoomListSnapshot
		}
	}
	return nil
}

func (x *Packet) GetPlayerInput() *PlayerInputMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *Packet) GetMatchSnapshot() *MatchSnapshotMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MatchSnapshot); ok {
			return x.MatchSnapshot
		}
	}
	return nil
}

func (x *Packet) GetPlayerKickRoomRequest() *PlayerKickRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerKickRoomRequest); ok {
			return x.PlayerKickRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetPlayerKickRoomResponse() *PlayerKickRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerKickRoomResponse); ok {
			return x.PlayerKickRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetPlayerRemoveRoom() *PlayerRemoveRoom {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayerRemoveRoom); ok {
			return x.PlayerRemoveRoom
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomResponseMessage() *JoinRoomResponseMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomResponseMessage); ok {
			return x.JoinRoomResponseMessage
		}
	}
	return nil
}

func (x *Packet) GetPlayersInRoomRequest() *PlayersInRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayersInRoomRequest); ok {
			return x.PlayersInRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetPlayersInRoomResponse() *PlayersInRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_PlayersInRoomResponse); ok {
			return x.PlayersInRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetRoomListRequestMessage() *RoomListRequestMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomListRequestMessage); ok {
			return x.RoomListRequestMessage
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,3,opt,name=id,proto3,oneof"`
}

type Packet_LoginRequest struct {
	LoginRequest *LoginRequestMessage `protobuf:"bytes,4,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequestMessage `protobuf:"bytes,5,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponseMessage `protobuf:"bytes,6,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponseMessage `protobuf:"bytes,7,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_CreateRoomRequest struct {
	CreateRoomRequest *CreateRoomRequestMessage `protobuf:"bytes,8,opt,name=create_room_request,json=createRoomRequest,proto3,oneof"`
}

type Packet_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequestMessage `protobuf:"bytes,9,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type Packet_LeaveRoomRequest struct {
	LeaveRoomRequest *LeaveRoomRequestMessage `protobuf:"bytes,10,opt,name=leave_room_request,json=leaveRoomRequest,proto3,oneof"`
}

type Packet_ReadyRequest struct {
	ReadyRequest *ReadyRequestMessage `protobuf:"bytes,11,opt,name=ready_request,json=readyRequest,proto3,oneof"`
}

type Packet_ReadyResponse struct {
	ReadyResponse *ReadyResponseMessage `protobuf:"bytes,12,opt,name=ready_response,json=readyResponse,proto3,oneof"`
}

type Packet_RoomStateSnapshot struct {
	RoomStateSnapshot *RoomStateSnapshotMessage `protobuf:"bytes,13,opt,name=room_state_snapshot,json=roomStateSnapshot,proto3,oneof"`
}

type Packet_MatchStarted struct {
	MatchStarted *MatchStartMessage `protobuf:"bytes,14,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type Packet_StartGame struct {
	StartGame *StartGameRequestMessage `protobuf:"bytes,15,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Packet_RoomSummaryMessage struct {
	RoomSummaryMessage *RoomSummaryMessage `protobuf:"bytes,16,opt,name=room_summary_message,json=roomSummaryMessage,proto3,oneof"`
}

type Packet_RoomListSnapshot struct {
	RoomListSnapshot *RoomListSnapshotMessage `protobuf:"bytes,17,opt,name=room_list_snapshot,json=roomListSnapshot,proto3,oneof"`
}

type Packet_PlayerInput struct {
	PlayerInput *PlayerInputMessage `protobuf:"bytes,18,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type Packet_MatchSnapshot struct {
	MatchSnapshot *MatchSnapshotMessage `protobuf:"bytes,19,opt,name=match_snapshot,json=matchSnapshot,proto3,oneof"`
}

type Packet_PlayerKickRoomRequest struct {
	PlayerKickRoomRequest *PlayerKickRoomRequest `protobuf:"bytes,20,opt,name=player_kick_room_request,json=playerKickRoomRequest,proto3,oneof"`
}

type Packet_PlayerKickRoomResponse struct {
	PlayerKickRoomResponse *PlayerKickRoomResponse `protobuf:"bytes,21,opt,name=player_kick_room_response,json=playerKickRoomResponse,proto3,oneof"`
}

type Packet_PlayerRemoveRoom struct {
	PlayerRemoveRoom *PlayerRemoveRoom `protobuf:"bytes,22,opt,name=player_remove_room,json=playerRemoveRoom,proto3,oneof"`
}

type Packet_JoinRoomResponseMessage struct {
	JoinRoomResponseMessage *JoinRoomResponseMessage `protobuf:"bytes,23,opt,name=join_room_response_message,json=joinRoomResponseMessage,proto3,oneof"`
}

type Packet_PlayersInRoomRequest struct {
	PlayersInRoomRequest *PlayersInRoomRequest `protobuf:"bytes,24,opt,name=players_in_room_request,json=playersInRoomRequest,proto3,oneof"`
}

type Packet_PlayersInRoomResponse struct {
	PlayersInRoomResponse *PlayersInRoomResponse `protobuf:"bytes,25,opt,name=players_in_room_response,json=playersInRoomResponse,proto3,oneof"`
}

type Packet_RoomListRequestMessage struct {
	RoomListRequestMessage *RoomListRequestMessage `protobuf:"bytes,26,opt,name=room_list_request_message,json=roomListRequestMessage,proto3,oneof"`
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_CreateRoomRequest) isPacket_Msg() {}

func (*Packet_JoinRoomRequest) isPacket_Msg() {}

func (*Packet_LeaveRoomRequest) isPacket_Msg() {}

func (*Packet_ReadyRequest) isPacket_Msg() {}

func (*Packet_ReadyResponse) isPacket_Msg() {}

func (*Packet_RoomStateSnapshot) isPacket_Msg() {}

func (*Packet_MatchStarted) isPacket_Msg() {}

func (*Packet_StartGame) isPacket_Msg() {}

func (*Packet_RoomSummaryMessage) isPacket_Msg() {}

func (*Packet_RoomListSnapshot) isPacket_Msg() {}

func (*Packet_PlayerInput) isPacket_Msg() {}

func (*Packet_MatchSnapshot) isPacket_Msg() {}

func (*Packet_PlayerKickRoomRequest) isPacket_Msg() {}

func (*Packet_PlayerKickRoomResponse) isPacket_Msg() {}

func (*Packet_PlayerRemoveRoom) isPacket_Msg() {}

func (*Packet_JoinRoomResponseMessage) isPacket_Msg() {}

func (*Packet_PlayersInRoomRequest) isPacket_Msg() {}

func (*Packet_PlayersInRoomResponse) isPacket_Msg() {}

func (*Packet_RoomListRequestMessage) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"\x1f\n" +
	"\vChatMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x19\n" +
	"\x17StartGameRequestMessage\"M\n" +
	"\x13LoginRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16RegisterRequestMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\x18CreateRoomRequestMessage\x12\x1c\n" +
	"\tmaxPlayer\x18\x01 \x01(\rR\tmaxPlayer\x12\x1a\n" +
	"\broomName\x18\x02 \x01(\tR\broomName\"0\n" +
	"\x16JoinRoomRequestMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\"\x18\n" +
	"\x16RoomListRequestMessage\"\xc1\x01\n" +
	"\x12RoomSummaryMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\x04R\x06roomId\x124\n" +
	"\aPlayers\x18\x03 \x03(\v2\x1a.packets.RoomPlayerMessageR\aPlayers\x12\x1c\n" +
	"\tmaxPlayer\x18\x04 \x01(\rR\tmaxPlayer\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.packets.RoomStatusR\x06status\"L\n" +
	"\x17RoomListSnapshotMessage\x121\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1b.packets.RoomSummaryMessageR\x05rooms\"\x19\n" +
	"\x17LeaveRoomRequestMessage\"/\n" +
	"\x13ReadyRequestMessage\x12\x18\n" +
	"\aisReady\x18\x01 \x01(\bR\aisReady\"H\n" +
	"\x14ReadyResponseMessage\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\aisReady\x18\x02 \x01(\bR\aisReady\"\x93\x01\n" +
	"\x11RoomPlayerMessage\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\x04R\bclientId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x18\n" +
	"\aisReady\x18\x04 \x01(\bR\aisReady\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\bR\x05owner\"M\n" +
	"\x17JoinRoomResponseMessage\x122\n" +
	"\x06player\x18\x01 \x01(\v2\x1a.packets.RoomPlayerMessageR\x06player\"0\n" +
	"\x16PlayerKickRoomResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"/\n" +
	"\x15PlayerKickRoomRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\"F\n" +
	"\x10PlayerRemoveRoom\x122\n" +
	"\x06player\x18\x01 \x01(\v2\x1a.packets.RoomPlayerMessageR\x06player\".\n" +
	"\x14PlayersInRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\"K\n" +
	"\x15PlayersInRoomResponse\x122\n" +
	"\x06Player\x18\x01 \x03(\v2\x1a.packets.RoomPlayerMessageR\x06Player\"\xb1\x01\n" +
	"\x18RoomStateSnapshotMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\x12\x1c\n" +
	"\tmaxPlayer\x18\x02 \x01(\rR\tmaxPlayer\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.packets.RoomStatusR\x06status\x122\n" +
	"\x06Player\x18\x04 \x03(\v2\x1a.packets.RoomPlayerMessageR\x06Player\"\xb8\x01\n" +
	"\x11MatchStartMessage\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x04R\x06roomId\x12\x18\n" +
	"\amatchId\x18\x02 \x01(\x04R\amatchId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\rR\x04slot\x12\x18\n" +
	"\amapSeed\x18\x05 \x01(\x04R\amapSeed\x12&\n" +
	"\x0estartsAtUnixMs\x18\x06 \x01(\x03R\x0estartsAtUnixMs\",\n" +
	"\x0eVector2Message\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"k\n" +
	"\x12PlayerInputMessage\x12\x18\n" +
	"\amatchId\x18\x01 \x01(\x04R\amatchId\x12;\n" +
	"\fmovePosition\x18\x02 \x01(\v2\x17.packets.Vector2MessageR\fmovePosition\"\xce\x01\n" +
	"\x17PlayerCellEntityMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x04R\aownerId\x123\n" +
	"\bposition\x18\x03 \x01(\v2\x17.packets.Vector2MessageR\bposition\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\rR\x02hp\x12\x18\n" +
	"\abiomass\x18\x05 \x01(\rR\abiomass\x12\x14\n" +
	"\x05level\x18\x06 \x01(\rR\x05level\x12\x14\n" +
	"\x05alive\x18\a \x01(\bR\x05alive\"\x82\x01\n" +
	"\x11CoreEntityMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x04R\aownerId\x123\n" +
	"\bposition\x18\x03 \x01(\v2\x17.packets.Vector2MessageR\bposition\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\rR\x02hp\"\x8a\x01\n" +
	"\x15NutrientEntityMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x123\n" +
	"\bposition\x18\x02 \x01(\v2\x17.packets.Vector2MessageR\bposition\x12\x14\n" +
	"\x05value\x18\x03 \x01(\rR\x05value\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"7\n" +
	"\x11WallEntityMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\"\x8b\x03\n" +
	"\x14MatchSnapshotMessage\x12\x18\n" +
	"\amatchId\x18\x01 \x01(\x04R\amatchId\x12\x1e\n" +
	"\n" +
	"serverTick\x18\x02 \x01(\x04R\n" +
	"serverTick\x12)\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x13.packets.MatchPhaseR\x05phase\x12(\n" +
	"\x0fphaseTimeLeftMs\x18\x04 \x01(\x03R\x0fphaseTimeLeftMs\x12B\n" +
	"\vplayerCells\x18\x05 \x03(\v2 .packets.PlayerCellEntityMessageR\vplayerCells\x120\n" +
	"\x05cores\x18\x06 \x03(\v2\x1a.packets.CoreEntityMessageR\x05cores\x12<\n" +
	"\tnutrients\x18\a \x03(\v2\x1e.packets.NutrientEntityMessageR\tnutrients\x120\n" +
	"\x05walls\x18\b \x03(\v2\x1a.packets.WallEntityMessageR\x05walls\"\x13\n" +
	"\x11OkResponseMessage\"-\n" +
	"\x13DenyResponseMessage\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x96\x0f\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12$\n" +
	"\x02id\x18\x03 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12C\n" +
	"\rlogin_request\x18\x04 \x01(\v2\x1c.packets.LoginRequestMessageH\x00R\floginRequest\x12L\n" +
	"\x10register_request\x18\x05 \x01(\v2\x1f.packets.RegisterRequestMessageH\x00R\x0fregisterRequest\x12=\n" +
	"\vok_response\x18\x06 \x01(\v2\x1a.packets.OkResponseMessageH\x00R\n" +
	"okResponse\x12C\n" +
	"\rdeny_response\x18\a \x01(\v2\x1c.packets.DenyResponseMessageH\x00R\fdenyResponse\x12S\n" +
	"\x13create_room_request\x18\b \x01(\v2!.packets.CreateRoomRequestMessageH\x00R\x11createRoomRequest\x12M\n" +
	"\x11join_room_request\x18\t \x01(\v2\x1f.packets.JoinRoomRequestMessageH\x00R\x0fjoinRoomRequest\x12P\n" +
	"\x12leave_room_request\x18\n" +
	" \x01(\v2 .packets.LeaveRoomRequestMessageH\x00R\x10leaveRoomRequest\x12C\n" +
	"\rready_request\x18\v \x01(\v2\x1c.packets.ReadyRequestMessageH\x00R\freadyRequest\x12F\n" +
	"\x0eready_response\x18\f \x01(\v2\x1d.packets.ReadyResponseMessageH\x00R\rreadyResponse\x12S\n" +
	"\x13room_state_snapshot\x18\r \x01(\v2!.packets.RoomStateSnapshotMessageH\x00R\x11roomStateSnapshot\x12A\n" +
	"\rmatch_started\x18\x0e \x01(\v2\x1a.packets.MatchStartMessageH\x00R\fmatchStarted\x12A\n" +
	"\n" +
	"start_game\x18\x0f \x01(\v2 .packets.StartGameRequestMessageH\x00R\tstartGame\x12O\n" +
	"\x14room_summary_message\x18\x10 \x01(\v2\x1b.packets.RoomSummaryMessageH\x00R\x12roomSummaryMessage\x12P\n" +
	"\x12room_list_snapshot\x18\x11 \x01(\v2 .packets.RoomListSnapshotMessageH\x00R\x10roomListSnapshot\x12@\n" +
	"\fplayer_input\x18\x12 \x01(\v2\x1b.packets.PlayerInputMessageH\x00R\vplayerInput\x12F\n" +
	"\x0ematch_snapshot\x18\x13 \x01(\v2\x1d.packets.MatchSnapshotMessageH\x00R\rmatchSnapshot\x12Y\n" +
	"\x18player_kick_room_request\x18\x14 \x01(\v2\x1e.packets.PlayerKickRoomRequestH\x00R\x15playerKickRoomRequest\x12\\\n" +
	"\x19player_kick_room_response\x18\x15 \x01(\v2\x1f.packets.PlayerKickRoomResponseH\x00R\x16playerKickRoomResponse\x12I\n" +
	"\x12player_remove_room\x18\x16 \x01(\v2\x19.packets.PlayerRemoveRoomH\x00R\x10playerRemoveRoom\x12_\n" +
	"\x1ajoin_room_response_message\x18\x17 \x01(\v2 .packets.JoinRoomResponseMessageH\x00R\x17joinRoomResponseMessage\x12V\n" +
	"\x17players_in_room_request\x18\x18 \x01(\v2\x1d.packets.PlayersInRoomRequestH\x00R\x14playersInRoomRequest\x12Y\n" +
	"\x18players_in_room_response\x18\x19 \x01(\v2\x1e.packets.PlayersInRoomResponseH\x00R\x15playersInRoomResponse\x12\\\n" +
	"\x19room_list_request_message\x18\x1a \x01(\v2\x1f.packets.RoomListRequestMessageH\x00R\x16roomListRequestMessageB\x05\n" +
	"\x03msg*>\n" +
	"\n" +
	"RoomStatus\x12\x17\n" +
	"\x13ROOM_STATUS_WAITING\x10\x00\x12\x17\n" +
	"\x13ROOM_STATUS_STARTED\x10\x01*T\n" +
	"\n" +
	"MatchPhase\x12\x17\n" +
	"\x13MATCH_PHASE_PREPARE\x10\x00\x12\x16\n" +
	"\x12MATCH_PHASE_ACTIVE\x10\x01\x12\x15\n" +
	"\x11MATCH_PHASE_ENDED\x10\x02B\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_packets_proto_goTypes = []any{
	(RoomStatus)(0),                  // 0: packets.RoomStatus
	(MatchPhase)(0),                  // 1: packets.MatchPhase
	(*ChatMessage)(nil),              // 2: packets.ChatMessage
	(*IdMessage)(nil),                // 3: packets.IdMessage
	(*StartGameRequestMessage)(nil),  // 4: packets.StartGameRequestMessage
	(*LoginRequestMessage)(nil),      // 5: packets.LoginRequestMessage
	(*RegisterRequestMessage)(nil),   // 6: packets.RegisterRequestMessage
	(*CreateRoomRequestMessage)(nil), // 7: packets.CreateRoomRequestMessage
	(*JoinRoomRequestMessage)(nil),   // 8: packets.JoinRoomRequestMessage
	(*RoomListRequestMessage)(nil),   // 9: packets.RoomListRequestMessage
	(*RoomSummaryMessage)(nil),       // 10: packets.RoomSummaryMessage
	(*RoomListSnapshotMessage)(nil),  // 11: packets.RoomListSnapshotMessage
	(*LeaveRoomRequestMessage)(nil),  // 12: packets.LeaveRoomRequestMessage
	(*ReadyRequestMessage)(nil),      // 13: packets.ReadyRequestMessage
	(*ReadyResponseMessage)(nil),     // 14: packets.ReadyResponseMessage
	(*RoomPlayerMessage)(nil),        // 15: packets.RoomPlayerMessage
	(*JoinRoomResponseMessage)(nil),  // 16: packets.JoinRoomResponseMessage
	(*PlayerKickRoomResponse)(nil),   // 17: packets.PlayerKickRoomResponse
	(*PlayerKickRoomRequest)(nil),    // 18: packets.PlayerKickRoomRequest
	(*PlayerRemoveRoom)(nil),         // 19: packets.PlayerRemoveRoom
	(*PlayersInRoomRequest)(nil),     // 20: packets.PlayersInRoomRequest
	(*PlayersInRoomResponse)(nil),    // 21: packets.PlayersInRoomResponse
	(*RoomStateSnapshotMessage)(nil), // 22: packets.RoomStateSnapshotMessage
	(*MatchStartMessage)(nil),        // 23: packets.MatchStartMessage
	(*Vector2Message)(nil),           // 24: packets.Vector2Message
	(*PlayerInputMessage)(nil),       // 25: packets.PlayerInputMessage
	(*PlayerCellEntityMessage)(nil),  // 26: packets.PlayerCellEntityMessage
	(*CoreEntityMessage)(nil),        // 27: packets.CoreEntityMessage
	(*NutrientEntityMessage)(nil),    // 28: packets.NutrientEntityMessage
	(*WallEntityMessage)(nil),        // 29: packets.WallEntityMessage
	(*MatchSnapshotMessage)(nil),     // 30: packets.MatchSnapshotMessage
	(*OkResponseMessage)(nil),        // 31: packets.OkResponseMessage
	(*DenyResponseMessage)(nil),      // 32: packets.DenyResponseMessage
	(*Packet)(nil),                   // 33: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	15, // 0: packets.RoomSummaryMessage.Players:type_name -> packets.RoomPlayerMessage
	0,  // 1: packets.RoomSummaryMessage.status:type_name -> packets.RoomStatus
	10, // 2: packets.RoomListSnapshotMessage.rooms:type_name -> packets.RoomSummaryMessage
	15, // 3: packets.JoinRoomResponseMessage.player:type_name -> packets.RoomPlayerMessage
	15, // 4: packets.PlayerRemoveRoom.player:type_name -> packets.RoomPlayerMessage
	15, // 5: packets.PlayersInRoomResponse.Player:type_name -> packets.RoomPlayerMessage
	0,  // 6: packets.RoomStateSnapshotMessage.status:type_name -> packets.RoomStatus
	15, // 7: packets.RoomStateSnapshotMessage.Player:type_name -> packets.RoomPlayerMessage
	24, // 8: packets.PlayerInputMessage.movePosition:type_name -> packets.Vector2Message
	24, // 9: packets.PlayerCellEntityMessage.position:type_name -> packets.Vector2Message
	24, // 10: packets.CoreEntityMessage.position:type_name -> packets.Vector2Message
	24, // 11: packets.NutrientEntityMessage.position:type_name -> packets.Vector2Message
	1,  // 12: packets.MatchSnapshotMessage.phase:type_name -> packets.MatchPhase
	26, // 13: packets.MatchSnapshotMessage.playerCells:type_name -> packets.PlayerCellEntityMessage
	27, // 14: packets.MatchSnapshotMessage.cores:type_name -> packets.CoreEntityMessage
	28, // 15: packets.MatchSnapshotMessage.nutrients:type_name -> packets.NutrientEntityMessage
	29, // 16: packets.MatchSnapshotMessage.walls:type_name -> packets.WallEntityMessage
	2,  // 17: packets.Packet.chat:type_name -> packets.ChatMessage
	3,  // 18: packets.Packet.id:type_name -> packets.IdMessage
	5,  // 19: packets.Packet.login_request:type_name -> packets.LoginRequestMessage
	6,  // 20: packets.Packet.register_request:type_name -> packets.RegisterRequestMessage
	31, // 21: packets.Packet.ok_response:type_name -> packets.OkResponseMessage
	32, // 22: packets.Packet.deny_response:type_name -> packets.DenyResponseMessage
	7,  // 23: packets.Packet.create_room_request:type_name -> packets.CreateRoomRequestMessage
	8,  // 24: packets.Packet.join_room_request:type_name -> packets.JoinRoomRequestMessage
	12, // 25: packets.Packet.leave_room_request:type_name -> packets.LeaveRoomRequestMessage
	13, // 26: packets.Packet.ready_request:type_name -> packets.ReadyRequestMessage
	14, // 27: packets.Packet.ready_response:type_name -> packets.ReadyResponseMessage
	22, // 28: packets.Packet.room_state_snapshot:type_name -> packets.RoomStateSnapshotMessage
	23, // 29: packets.Packet.match_started:type_name -> packets.MatchStartMessage
	4,  // 30: packets.Packet.start_game:type_name -> packets.StartGameRequestMessage
	10, // 31: packets.Packet.room_summary_message:type_name -> packets.RoomSummaryMessage
	11, // 32: packets.Packet.room_list_snapshot:type_name -> packets.RoomListSnapshotMessage
	25, // 33: packets.Packet.player_input:type_name -> packets.PlayerInputMessage
	30, // 34: packets.Packet.match_snapshot:type_name -> packets.MatchSnapshotMessage
	18, // 35: packets.Packet.player_kick_room_request:type_name -> packets.PlayerKickRoomRequest
	17, // 36: packets.Packet.player_kick_room_response:type_name -> packets.PlayerKickRoomResponse
	19, // 37: packets.Packet.player_remove_room:type_name -> packets.PlayerRemoveRoom
	16, // 38: packets.Packet.join_room_response_message:type_name -> packets.JoinRoomResponseMessage
	20, // 39: packets.Packet.players_in_room_request:type_name -> packets.PlayersInRoomRequest
	21, // 40: packets.Packet.players_in_room_response:type_name -> packets.PlayersInRoomResponse
	9,  // 41: packets.Packet.room_list_request_message:type_name -> packets.RoomListRequestMessage
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[31].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Id)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_CreateRoomRequest)(nil),
		(*Packet_JoinRoomRequest)(nil),
		(*Packet_LeaveRoomRequest)(nil),
		(*Packet_ReadyRequest)(nil),
		(*Packet_ReadyResponse)(nil),
		(*Packet_RoomStateSnapshot)(nil),
		(*Packet_MatchStarted)(nil),
		(*Packet_StartGame)(nil),
		(*Packet_RoomSummaryMessage)(nil),
		(*Packet_RoomListSnapshot)(nil),
		(*Packet_PlayerInput)(nil),
		(*Packet_MatchSnapshot)(nil),
		(*Packet_PlayerKickRoomRequest)(nil),
		(*Packet_PlayerKickRoomResponse)(nil),
		(*Packet_PlayerRemoveRoom)(nil),
		(*Packet_JoinRoomResponseMessage)(nil),
		(*Packet_PlayersInRoomRequest)(nil),
		(*Packet_PlayersInRoomResponse)(nil),
		(*Packet_RoomListRequestMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
